name: Publish
on:
  release:
    types: [released]

jobs:
  package-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ deb, rpm ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Packages
        run: ./mvnw -B clean package "-DskipTests=true" "-Dskip.jpackage=false" "-Djpackage-cfg=jpackage-linux.cfg" "-Djpackage.type=${{ matrix.type }}"
      - name: Add generated binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: reta-${{ matrix.type }}
          path: ./RETA-packaging/target/reta*.${{ matrix.type }}
          if-no-files-found: error

  package-windows:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install DOTNET
        uses: actions/setup-dotnet@v1
      - name: Install WiX
        run: dotnet tool install --global wix
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build Packages
        run: ./mvnw -B clean package "-DskipTests=true" "-Dskip.jpackage=false" "-Djpackage-cfg=jpackage-windows.cfg" "-Djpackage.type=msi"
      - name: Add generated binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: reta-msi
          path: ./RETA-packaging/target/reta*.msi
          if-no-files-found: error

  package-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: build RETA
        run: ./mvnw -B clean package -DskipTests=true -Dskip.assembly=false
      - name: Add generated binaries to artifact
        uses: actions/upload-artifact@v4
        with:
          name: reta-assembly
          path: ./RETA-packaging/target/reta-*.zip
          if-no-files-found: error

  upload:
    runs-on: ubuntu-latest
    needs: [ package-linux, package-windows, package-archive ]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Upload to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls
          gh release upload ${{ github.event.release.tag_name }} $(ls reta-*.msi reta*.deb reta*.rpm reta-*.zip 2>/dev/null)
    